name: Licensed

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-licensed:
    name: Licensed # The reusable workflow can be found here: https://github.com/actions/reusable-workflows/blob/main/.github/workflows/licensed.yml
    #uses: actions/reusable-workflows/.github/workflows/licensed.yml@main
    uses: IvanZosimov/reusable-workflows/.github/workflows/licensed.yml@main